apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: say-hello
      image: docker/whalesay
      script: |
        #!/usr/bin/env sh
        cowsay "Hello Tekton"
