apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-trigger-template
spec:
  params:
    - default: master
      description: The git revision
      name: revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: test-pipeline-run-
      spec:
        params:
          - name: repo-url
            value: 'https://github.com/jo8s/Breakout'
          - name: revision
            value: $(tt.params.revision)
        pipelineRef:
          name: test-pipeline
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: shared-workspace-pvc
