apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: start-buildconfig-run-
spec:
  taskRef:
    name: start-buildconfig
  params:
    - name: buildconfig-name
      value: my-python-app-build
